services:
  ua-cloudlibrary:
    image: ${DOCKER_REGISTRY-}uacloudlibrary
    ports:
      - 8443:443
    build:
      context: .
      dockerfile: UACloudLibraryServer/Dockerfile
    environment:
        PostgreSQLUsername: uacloudlib
        PostgreSQLPassword: uacloudlib
        ServicePassword: uacloudlib
        PostgreSQLEndpoint: db
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: "https://+:443;http://+:8080"
        # Tell Kestrel to use the PFX certificate and (if applicable) its password.
        Kestrel__Certificates__Default__Path: /root/.aspnet/https/aspnetcore-localhost-CBC034E9DB030041F729D983C98235565A086D4F.pfx
        Kestrel__Certificates__Default__Password: ""
    volumes:
        # Mount your host certificate directory into /root/.aspnet/https
        - ${HOME}/.aspnet/dev-certs/https:/root/.aspnet/https:ro
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: uacloudlib
      POSTGRES_USER: uacloudlib
      POSTGRES_DB: uacloudlib
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - 80:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: no-reply@opcfoundation.org
      PGADMIN_DEFAULT_PASSWORD: uacloudlib
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./local-dev-docker/docker_pgadmin_servers.json:/pgadmin4/servers.json
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:*:uacloudlib:uacloudlib' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped
